version: '3'

services:
  # Main database
  postgres:
    image: postgres
    container_name: ${PGDATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:5432

  # Reverse-proxy for backend and frontend servers
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./priv/cert/:/etc/nginx/ssl/
      - ./webui/dist/:/usr/share/nginx/html/
    ports:
      - 443:443
    # depends_on:
    #   - backend
    #   - frontend
    # backend:
    #   image: elixir
    #   volumes:
    #     - ./:/srv/debora/
    #   env_file:
    #     - ./env/.env.dev
    #   depends_on:
    #     - postgres
    #   command:
    #     - bash
    #     - -c
    #     - |
    #       cd /srv/debora/
    #       PGHOST=postgres
    #       PGPORT=5432
    #       mix local.hex --force
    #       mix ecto.migrate
    #       mix phx.server

    # frontend:
    #   image: node
    #   volumes:
    #     - ./webui/:/srv/debora/
    #     - ./env/:/srv/debora/env/
    #   environment:
    #     - VITE_CLIENT_ID=$VITE_CLIENT_ID
    #   depends_on:
    #     - backend
    #   command:
    #     - bash
    #     - -c
    #     - |
    #       cd /srv/debora/
    #       npm run dev
