version: '3'

services:
  # Main database
  postgres:
    image: postgres
    container_name: ${PGDATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./priv/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PGPORT}:5432

  # Reverse-proxy for backend and frontend servers
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./priv/cert/:/etc/nginx/ssl/
      - ./webui/dist/:/usr/share/nginx/html/
    ports:
      - 443:443
