version: '3'

services:
  postgres:
    image: postgres
    container_name: ${PGDATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:5432

  # pgadmin:
  #   image: dpage/pgadmin4:6.15
  #   container_name: ${PGDATABASE}_ui
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGUSER}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
  #   ports:
  #     - ${PGADMIN_PORT}:80

  nginx:
    image: nginx
    container_name: debora_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./priv/cert:/etc/nginx/ssl
      - ./webui/dist:/usr/share/nginx/html
    network_mode: host
