version: '3'

services:
  postgres:
    image: postgres
    container_name: ${PGDATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - ${PGPORT}:5432

  nginx:
    image: nginx
    container_name: debora_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./priv/cert:/etc/nginx/ssl
      - ./webui/dist:/usr/share/nginx/html
    ports:
      - 443:443
